apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
spec:
  type: NodePort  # Chọn loại NodePort
  ports:
    - port: 8080       # Cổng dịch vụ
      targetPort: 8080 # Cổng container
      nodePort: 30088   # Cổng bên ngoài mà bạn muốn sử dụng
  selector:
    app: keycloak
